-- NUVEXA HUB V8.3
-- Cloud email roles for Owner/Admin access.
-- Run once in Supabase Dashboard > SQL Editor.

begin;

create table if not exists public.platform_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  display_name text not null default '',
  role text not null default 'customer'
    check (role in ('owner','admin','seller','customer')),
  active boolean not null default true,
  permissions jsonb not null default '{}'::jsonb,
  added_by text,
  protected boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.platform_users_normalize()
returns trigger
language plpgsql
as $$
begin
  new.email := lower(trim(new.email));
  new.added_by := nullif(lower(trim(coalesce(new.added_by, ''))), '');
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists platform_users_normalize_trigger on public.platform_users;
create trigger platform_users_normalize_trigger
before insert or update on public.platform_users
for each row execute function public.platform_users_normalize();

create or replace function public.platform_users_protect_owner()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' and old.protected then
    raise exception 'The protected platform owner cannot be deleted.';
  end if;

  if tg_op = 'UPDATE' and old.protected then
    if new.email <> old.email or new.role <> 'owner' or new.active is not true or new.protected is not true then
      raise exception 'The protected platform owner cannot be disabled or downgraded.';
    end if;
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists platform_users_protect_owner_trigger on public.platform_users;
create trigger platform_users_protect_owner_trigger
before update or delete on public.platform_users
for each row execute function public.platform_users_protect_owner();

-- Seed the initial owner before enabling client policies.
insert into public.platform_users
  (email, display_name, role, active, permissions, protected, added_by)
values
  ('amerihgg@gmail.com', 'صاحب المنصة', 'owner', true, '{"all": true}'::jsonb, true, 'system')
on conflict (email) do update set
  display_name = excluded.display_name,
  role = 'owner',
  active = true,
  protected = true,
  permissions = '{"all": true}'::jsonb,
  updated_at = now();

alter table public.platform_users enable row level security;

create or replace function public.is_platform_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.platform_users pu
    where pu.active is true
      and pu.role = 'owner'
      and lower(pu.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_platform_owner() from public;
grant execute on function public.is_platform_owner() to authenticated;

revoke all on public.platform_users from anon;
grant select, insert, update, delete on public.platform_users to authenticated;
grant usage, select on sequence public.platform_users_id_seq to authenticated;

drop policy if exists "platform users read own or owner" on public.platform_users;
create policy "platform users read own or owner"
on public.platform_users
for select
to authenticated
using (
  lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  or public.is_platform_owner()
);

drop policy if exists "platform owner inserts users" on public.platform_users;
create policy "platform owner inserts users"
on public.platform_users
for insert
to authenticated
with check (public.is_platform_owner());

drop policy if exists "platform owner updates users" on public.platform_users;
create policy "platform owner updates users"
on public.platform_users
for update
to authenticated
using (public.is_platform_owner())
with check (public.is_platform_owner());

drop policy if exists "platform owner deletes users" on public.platform_users;
create policy "platform owner deletes users"
on public.platform_users
for delete
to authenticated
using (public.is_platform_owner());

commit;
